### ISSUE TITLE
Safety Features

### ISSUE THREAD

**Issue by jjporterNex** [JBarker90/bash_scripts-nx#1]
Noticed that it does not check if running the command to create a new DKIM, if there is already a DKIM.

There is already a command in it to check for this: dkim -f

Should have some sort of check to make sure it doesn't overwrite DKIM, and then maybe can introduce a force flag in case the user wants to

**Comment by JBarker90** [comment]
Thanks for bringing this up. I added an if statement that checks if the DKIM key file already exists before proceeding to create one.  I'll need to see if the iworx command used to create the DKIM already has a force option to overwrite the key before adding any force flag. Here's the commit with my update

https://github.com/JBarker90/bash_scripts-nx/commit/0de339a12f3ebd4acfaec1761b06fda2948d8c2e

**Comment by JBarker90** [comment]
Implemented -f flag to force in a newer build of the script. Closing
